precommit needs angular too

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -4,24 +4,56 @@ on:
   push:
 
 jobs:
-  python-tests:
-    strategy:
-      fail-fast: false
-      matrix:
-        os: [ubuntu-latest]
-        python-version: ['3.9', '3.12']
-    runs-on: ${{ matrix.os }}
+  lint:
+    runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
       - name: Check out cbl-workflow repository
         uses: actions/checkout@v4
         with:
           repository: SEED-platform/cbl-workflow
-          path: cbl-workflow
-      - name: Move cbl-workflow to expected location
+          path: ../cbl-workflow
+      - name: Set up Python 3.12
+        uses: actions/setup-python@v5.6.0
+        with:
+          python-version: '3.12'
+      - name: Install Poetry
+        uses: snok/install-poetry@v1.4.1
+      - name: Install Python dependencies
+        working-directory: flask_app
         run: |
-          mkdir -p ../
-          mv cbl-workflow ../cbl-workflow  # Move to one level up
+          python -m pip install --upgrade pip
+          poetry install
+      - uses: actions/setup-node@v4
+        with:
+          node-version: 20
+      - name: Install Angular dependencies
+        working-directory: angular-app
+        run: |
+          npm install
+          cp src/environments/environment.ts.template src/environments/environment.ts
+      - name: Run pre-commit
+        run: |
+          poetry run pre-commit run --all-files || {
+            echo "Pre-commit failed. Here are the changes:"
+            git diff
+            exit 1
+          }
+
+  python-tests:
+    needs: lint
+    strategy:
+      fail-fast: false
+      matrix:
+        python-version: ['3.9', '3.12']
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+      - name: Check out cbl-workflow repository
+        uses: actions/checkout@v4
+        with:
+          repository: SEED-platform/cbl-workflow
+          path: ../cbl-workflow
       - name: Set up Python ${{ matrix.python-version }}
         uses: actions/setup-python@v5.6.0
         with:
@@ -33,13 +65,6 @@ jobs:
         run: |
           python -m pip install --upgrade pip
           poetry install
-      - name: Run pre-commit
-        run: |
-          poetry run pre-commit run --all-files || {
-            echo "Pre-commit failed. Here are the changes:"
-            git diff
-            exit 1
-          }
       - name: Run Python Tests
         env:
           MAPBOX_ACCESS_TOKEN: ${{ secrets.MAPBOX_ACCESS_TOKEN }}
@@ -47,6 +72,7 @@ jobs:
         run: poetry run pytest
 
   angular-tests:
+    needs: lint
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
