run angular and python tests separate

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -4,7 +4,7 @@ on:
   push:
 
 jobs:
-  test:
+  python-tests:
     strategy:
       fail-fast: false
       matrix:
@@ -33,6 +33,23 @@ jobs:
         run: |
           python -m pip install --upgrade pip
           poetry install
+      - name: Run pre-commit
+        run: |
+          poetry run pre-commit run --all-files || {
+            echo "Pre-commit failed. Here are the changes:"
+            git diff
+            exit 1
+          }
+      - name: Run Python Tests
+        env:
+          MAPBOX_ACCESS_TOKEN: ${{ secrets.MAPBOX_ACCESS_TOKEN }}
+          MAPQUEST_API_KEY: ${{ secrets.MAPQUEST_API_KEY }}
+        run: poetry run pytest
+
+  angular-tests:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
       - uses: actions/setup-node@v4
         with:
           node-version: 20
@@ -50,18 +67,6 @@ jobs:
         run: |
           # Verify the app builds successfully before running tests
           npm run build
-      - name: Run pre-commit
-        run: |
-          poetry run pre-commit run --all-files || {
-            echo "Pre-commit failed. Here are the changes:"
-            git diff
-            exit 1
-          }
-      - name: Run Python Tests
-        env:
-          MAPBOX_ACCESS_TOKEN: ${{ secrets.MAPBOX_ACCESS_TOKEN }}
-          MAPQUEST_API_KEY: ${{ secrets.MAPQUEST_API_KEY }}
-        run: poetry run pytest
       - name: Run Angular Tests
         env:
           MAPBOX_ACCESS_TOKEN: ${{ secrets.MAPBOX_ACCESS_TOKEN }}
@@ -73,9 +78,8 @@ jobs:
           # This executes all *.spec.ts files in the project
           ng test --watch=false --browsers=ChromeHeadless --code-coverage --progress
       - name: Upload Angular Test Coverage
-        if: matrix.python-version == '3.12' # Only upload once per build
         uses: actions/upload-artifact@v4
         with:
-          name: angular-coverage-${{ matrix.os }}-py${{ matrix.python-version }}
+          name: angular-coverage
           path: angular-app/coverage/
           retention-days: 7
